name: 错误反馈
description: 反馈脚本或样式中的错误
title: "[Bug] "
labels: []
assignees:
  - CKylinMC
body:
  - type: dropdown
    id: target
    attributes:
      label: 目标
      description: 是哪一个脚本或样式出现了问题？
      multiple: false
      options:
        - 脚本：视频页面常驻显示AV/BV号
        - 脚本：关注管理器
        - 脚本：视频旋转和缩放
        - 脚本：站内私信一键已读
        - 脚本：站内链接信息显示BilibiliLinksInfos
        - 脚本：修改迷你播放器大小位置
        - 脚本：评论过滤
        - 脚本：平滑展开视频信息
        - 脚本：宽屏模式不重定位
        - 脚本：AB循环
        - 脚本：评论区屏蔽工具
        - 样式：哔哩哔哩移除评论区
        - 样式：播放器特效
        - 样式：YTB移除评论区
        - 样式：移除评分
        - 样式：移除高能弹幕图标
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 脚本版本号
      description: 请输入脚本的版本号
      placeholder: 如：v1.0.0
    validations:
      required: true
  - type: markdown
    id: bugdesc
    attributes:
      value: "## 描述出现的问题"
