name: 错误反馈
description: 反馈脚本或样式中的错误
title: "[Bug] "
labels: []
assignees:
  - CKylinMC
body:
  - type: dropdown
    attributes:
      label: 目标
      description: 是哪一个脚本或样式出现了问题？
      multiple: false
      options:
        - label: 脚本-视频页面常驻显示AV/BV号
        - label: 脚本-关注管理器
        - label: 脚本-视频旋转和缩放
        - label: 脚本-站内私信一键已读
        - label: 脚本-站内链接信息显示 BilibiliLinksInfos
        - label: 脚本-修改迷你播放器大小位置
        - label: 脚本-评论过滤
        - label: 脚本-平滑展开视频信息
        - label: 脚本-宽屏模式不重定位
        - label: 脚本-AB循环
        - label: 脚本-评论区屏蔽工具
        - label: 样式-移除评论区
        - label: 样式-播放器特效
        - label: 样式-移除评论区
        - label: 样式-移除评分
        - label: 样式-移除高能弹幕图标
    validations:
      required: true
  - type: textarea
    attributes:
      label: 脚本版本号
      description: 请输入脚本的版本号
      placeholder: 如：v1.0.0
      value: version
    validations:
      required: true
  - type: markdown
    attributes:
      value: "描述出现的问题"
