name: 建议和功能请求
description: 提出建议或功能需求
title: "[IDEA] "
labels: []
assignees:
  - CKylinMC
body:
  - type: dropdown
    id: target
    attributes:
      label: 目标
      description: 关于哪个脚本或样式？
      multiple: true
      options:
        - 脚本：视频页面常驻显示AV/BV号
        - 脚本：关注管理器
        - 脚本：视频旋转和缩放
        - 脚本：站内私信一键已读
        - 脚本：不要Sentry
        - 脚本：站内链接信息显示BilibiliLinksInfos
        - 脚本：修改迷你播放器大小位置
        - 脚本：评论过滤
        - 脚本：平滑展开视频信息
        - 脚本：宽屏模式不重定位
        - 脚本：AB循环
        - 脚本：评论区屏蔽工具
        - 样式：哔哩哔哩移除评论区
        - 样式：播放器特效
        - 样式：YTB移除评论区
        - 样式：移除评分
        - 样式：移除高能弹幕图标
        - 综合或其他
    validations:
      required: true
  - type: textarea
    id: desp
    attributes:
      label: 描述你的想法
      description: 尽可能详细地描述你的建议或功能需求
      placeholder: 描述建议...
    validations:
      required: true
